project_id = "eofedcncgpcpvxoibkjm"

[functions.transcribe]
verify_jwt = false

[functions.transcribe-chunk]
verify_jwt = false

[functions.generate-scenes]
verify_jwt = false

[functions.render-video]
verify_jwt = false

[functions.generate-tts]
verify_jwt = false

[functions.generate-tts-chunk]
verify_jwt = false

[functions.generate-scene-parts]
verify_jwt = false
